language: node_js

services:
  - mongodb # runs a mongo process on port 27017

node_js:
  - lts/* # latest 'stable' version

before_script:
  # mongo does not immediately accept connections
  - sleep 5
  # create a new database named "testdb" and create a test db user for it
  - mongo testdb --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  # install dependencies
  - cd api && npm install

script:
  - make tests

cache: npm
